


# Permalinks
permalink:        pretty

# Setup
title:            coursecal
tagline:          'A library for building course calendars'
description:      'Develop course calendars from simple lists in plain-text files'

url: 'http://neelsmith.github.io'
baseurl: '/coursecal/'


author:
  name:           'Neel Smith'


links:
  - title:  Github repository
    url:  https://github.com/neelsmith/coursecal
    external: true
